apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  selector:
    matchLabels:
      app: jenkins-master
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: github-private-key-volume
              mountPath: /var/jenkins_home/.ssh
              readOnly: true
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: github-private-key-volume
          secret:
            secretName: github-private-key-secret